### ISSUE TITLE
How do I reduce the batch size for training ?

### ISSUE THREAD

**Issue by YacineDeghaies** [isl-org/ZoeDepth#121]
I've tried adding batch_size to the COMMON_CONFIG dictionary in config.py

![Screenshot 2024-07-08 at 05 06 30](https://github.com/isl-org/ZoeDepth/assets/56239998/b6cb2703-4acf-4183-8d09-348b7c8fd60b)

but I'm still getting this error

![Screenshot 2024-07-08 at 05 07 18](https://github.com/isl-org/ZoeDepth/assets/56239998/99bf667e-7c69-4ff8-9ee7-e3d81d83ef7b)

**Comment by dung2603** [comment]
Open this file and change batch size https://github.com/isl-org/ZoeDepth/blob/main/zoedepth/models/zoedepth/config_zoedepth.json
