### ISSUE TITLE
Different result between demo and local test

### ISSUE THREAD

**Issue by yang778** [isl-org/ZoeDepth#14]
As shown below, I used same input image, but generate different depth result, the main diff is that demo sky has no depth, what's the reason?
1) demo result: ![image](https://user-images.githubusercontent.com/8702752/225285488-b0f226a0-5516-45ae-ad2f-33625d292d63.png)
2) local result using nk pretrained model: ![image](https://user-images.githubusercontent.com/8702752/225285561-0fc9b4ca-f30a-4e08-a38f-b0e05e2671c3.png)

**Comment by shariqfarooq123** [comment]
Currently, ZoeD_N is the active model on the demo
