### ISSUE TITLE
why are the perfomances lower than the figuers on the paper

### ISSUE THREAD

**Issue by jisu9867** [isl-org/ZoeDepth#17]
how can i get your perfomance on the metrics?
if i train your model on my local computer(all the same config), i can get the poor perfomances than yours. is there any factors that affect the perfomance?
i know it's my problem. Can you give me some advice for this problem?

**Comment by shariqfarooq123** [comment]
Numbers should be reproducible as we have tested rigorously. What metrics do you get? Do you make sure you are using config_mode="eval" mode for evaluation?

**Comment by shariqfarooq123** [comment]
No, these warnings are about "run time/speed" performance and are not related to the accuracy of the model. 

- What metrics do you get, for example, what are the abs_rel, rmse and delta_1 values?  
- How did you set up the datasets? Are you making sure you are evaluating on the raw NYU dataset and NOT the inpainted ground truths?

**Comment by shariqfarooq123** [comment]
These are close enough. But I would still suggest checking for different seeds.

**Comment by shariqfarooq123** [comment]
Closing this issue. Please feel free to re-open if you want to follow up on this.
