### ISSUE TITLE
A question about evaluation on SUNRGBD dataset

### ISSUE THREAD

**Issue by whyxz** [isl-org/ZoeDepth#18]
Greetings, I would like to request assistance with testing on SUNRGBD dataset. It appears that the official SUNRGBD dataset did not provide a division between the training and testing sets. How did you conduct your testing?

**Comment by shariqfarooq123** [comment]
SUNRGBD has 5050 test images. Have a look at [https://github.com/ankurhanda/sunrgbd-meta-data)](https://github.com/ankurhanda/sunrgbd-meta-data](https://github.com/ankurhanda/sunrgbd-meta-data)](https://github.com/ankurhanda/sunrgbd-meta-data).

**Comment by whyxz** [comment]
> Greetings, SUNRGBD has 5050 test images. Have a look at https://github.com/ankurhanda/sunrgbd-meta-data .

Thank you for reply!
