### ISSUE TITLE
How to increase output depth map resolution?

### ISSUE THREAD

**Issue by oscarqht** [isl-org/ZoeDepth#2]
Hi. Great work and thanks for sharing the colab notebook! I noticed that the on the colab notebook, output depth map appears to be of relatively low resolution compared to the input image, which could result in some fuzziness. As such, I am curious to know whether there is a way to increase the output depth map resolution.

If it is not too much trouble, could you kindly point me to the relevant section of the notebook where I can make the necessary changes? I would be incredibly grateful for your help in this regard :)

![image](https://user-images.githubusercontent.com/165961/222314040-39031497-207c-4886-9cd4-387ce8b90cba.png)

**Comment by talasalim** [comment]
I also used the notebook, do you know how we can add code to extract the metric depth at each pixel?

**Comment by razorx89** [comment]
I am also curious how we could improve on the depth map resolution. I think the current pre-trained models won't be able to generate higher resolutions. However, are there any plans to use backbones with larger image sizes? Or are there any tricks to generate e.g. a sliding window inference with recalibration based on other predictions? For example,  I cropped a high resolution image into multiple non-overlapping images and stitched the resulting depth maps together, but the boundary artifacts are clearly visible and there are also some depth inconsistencies between the individual crops.

A hierarchical approach could be the way to go, using ZoeDepth for depth estimation at the full image but coarse resolution and afterwards using this as an additional input to give guidance to a decoder which predicts on a fine resolution crop.

**Comment by m0o0scar** [comment]
[Boosting Monocular Depth Estimation Models to High-Resolution via Content-Adaptive Multi-Resolution Merging – Yağız Aksoy](http://yaksoy.github.io/highresdepth/) this research looks like a good place to start @razorx89
