### ISSUE TITLE
 Re-training ZoeDepth Model on Custom Indoor Dataset

### ISSUE THREAD

**Issue by AshkanGanj** [isl-org/ZoeDepth#29]
Hello and thank you for open-sourcing the ZoeDepth project! It has been incredibly useful, and I truly appreciate the work put into it.

I am currently facing some difficulties re-training the ZoeDepth model on a custom indoor dataset that I have prepared. It would be great to have some documentation or guidance on how to accomplish this task, as I believe it would benefit other users as well.

Please provide any relevant documentation or instructions for re-training the ZoeDepth model on custom datasets. This would be very helpful for users working with unique data sources.
A step-by-step guide with this information on how to run training on a custom dataset would also be greatly appreciated.

        1. How to prepare the dataset (formatting, pre-processing, etc.) 
        2. Modifications needed to the model or training configurations
        3. How to initiate the training process with the custom dataset
       
I understand that creating such documentation might take some time, but any help you can provide would be highly valuable.

Thank you in advance for your assistance and support.

**Comment by ValeriaIM** [comment]
Hello, I'm also interested in retraining on my dataset. If you can figure this out, I would be grateful for your help

**Comment by lxy5513** [comment]
@AshkanGanj 
Maybe you can follow this [https://medium.com/@bhaskarbose1998/monocular-depth-estimation-using-zoedepth-our-experience-42fa5974cb59](url)
Hope it can help you

**Comment by Richerhooders** [comment]
> @AshkanGanj Maybe you can follow this [https://medium.com/@bhaskarbose1998/monocular-depth-estimation-using-zoedepth-our-experience-42fa5974cb59](url) Hope it can help you
Hello, I can't see the content in this link. Can you provide a new link or give me some prompts？

**Comment by Haozong-Zeng** [comment]
> @AshkanGanj Maybe you can follow this [https://medium.com/@bhaskarbose1998/monocular-depth-estimation-using-zoedepth-our-experience-42fa5974cb59](url) Hope it can help you

Hello, this link seems no longer available.

**Comment by AshkanGanj** [comment]
Hi I just wanted to share that I managed to train zoedepth on a new dataset. My code is available in this repo: 
[https://github.com/cake-lab/Mobile-AR-Depth-Estimation](https://github.com/cake-lab/Mobile-AR-Depth-Estimation)

**Comment by YacineDeghaies** [comment]
@AshkanGanj congrats !
Can you please share how the structure of my custom dataset should looks like ?
also, do you have any tips on how to train on my custom dataset ? My dataset is composed of rgb images + their relative depth maps.

Thanks :D
