### ISSUE TITLE
Training is extremely unstable

### ISSUE THREAD

**Issue by kwea123** [isl-org/ZoeDepth#42]
<img width="221" alt="截圖 2023-06-15 下午1 47 02" src="https://github.com/isl-org/ZoeDepth/assets/11364490/f8c42443-6045-4a89-8d02-4c0cee843d03">

I ran the training multiple times with the default parameters, sometimes everything trains smoothly, but most of the times training fails at a very early stage and produces images like above

**Comment by kwea123** [comment]
this code just works randomly, it "works as expected".

**Comment by longyangqi** [comment]
Similar Results:
![image](https://github.com/isl-org/ZoeDepth/assets/13297107/2b050ca6-64a0-426c-a8f2-fc6a34fe1b47)

Have you solve the problem now？
