### ISSUE TITLE
speed compared to other algorithm

### ISSUE THREAD

**Issue by CHYjeremy** [isl-org/ZoeDepth#57]
Hi authors of zoedepth

first of all, much thx to your work,

i would like to ask, how is the inference speed as compared to other algorithm?

 because we need it to run on many many pics, so speed matter a lot.

**Comment by Linkersem** [comment]
Hi, did you test the speed to inference a picture?

**Comment by philippwulff** [comment]
For me it is ~1.5s per 384x1280 img

**Comment by EveningLin** [comment]
@philippwulff 
would you please share the testing environment
